import { HydrationProvider, Client } from "react-hydration-provider";
import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '../styles/Home.module.css';
import Board from "../containers/Board";
import styled from "styled-components";
import IndexLayout from '../styles/globals';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <HydrationProvider>
      <Client>
        <Head>
            <title>🐱‍👤 Tic-Tac-Toc-Cat</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
          <IndexLayout>
            <main className={styles.main}>
              <Board />
            </main>
          </IndexLayout>
      </Client>
    </HydrationProvider>
  );
};
